num1 = int(input('Quantos números quer mostrar ?'))
cont = 1
a1 = 0
a2 = 1
print(f'{a1} {a2} ', end='')
while cont <= num1:
    a3 = a1 + a2
    print(f'{a3} ', end='')
    a1 = a2
    a2 = a3
    cont += 1